---
title: "A novel, cost-effective methodology to create and evaluate stand-level ecosystem maps with machine-learning"
author: William H. MacKenzie, Genevieve C. Perkins, Kiri S. Daust, Peter K. Ott, Robert A. MacMillan, Brandon Heung, Che Elkin, Colin Chisholm, Pam Dykstra2, Deepa Filatow, Mike Ryan, Tim Salkeld. Tomislav Hengl.
format:
  elsevier-pdf:
    journal: 
      name: ecological informatics
      formatting: review
      model: 3p
      cite-style: authoryear
editor: visual
---

# Abstract 

Ecosystem maps are a valuable tool for ecosystem-based management. Existing ecosystem mapping approaches, which typically use expert models or manual air photo  interpretation, are confounded by subjectivity, are difficult to update, have unsatisfactory delineation of uncommon ecosystems, and require an expensive independent program to assess map accuracy. Although. Aa data-driven, machine learning approach to ecosystem mapping has the potential to address these limitations   but,  the prohibitive costs of current methods for acquiring field reliable training data have limited application in practice. We present a cost-efficient sample design and field data collection protocol that utilizes triangular line-intercept transects based on a sliced  , cost-constrained conditioned Latin hypercube sampling of a small set of ecologically relevant landscape-level predictors. Five-site slices are used in this scalable design to provide spatially distinct units applied to both generate clusters of training data for the construction of machine-learning ecosystem models and use as a spatially distinct assessment unit for the statistical evaluation of map accuracy. To identify potential model extrapolation problems, the stand-level predictor space of the training data is compared to the entire map to quantify the amount of area with unsampled predictor combinations. We iteratively construct and evaluate multiple PEM models from the training data leaving out a single assessment slice at   each iteration and we generate spatial and aspatial accuracy statistics for each iteration. Novel accuracy metrics are reported that account for map unit abundance, uncertainty in identification and overlap of ecological classes (fuzzy class membership), and spatial misregistration between field observation locations and predictions at grid locations. The metrics are maximized through a map unit balance optimization of the training set. We apply this methodology     to sample, build, and evaluate a stand-level ecosystem map in a low boreal forest study area. A Random Forests machine learner is applied to a selected suite of spatial predictors derived from LiDAR. We show that the presentedour sample design successfully samples both important stand-level predictor distributions and a representative set of ecosystem map units in our case study area, while reducing sample costs by an order of magnitude compared to single point sampling  . Machine-learning models trained with data from as few as 30 of our sample transects , representing 3-4 crew-days of effort, generate a stand-level forest ecosystem map assessed to deliver 80% +/- 10% agreement on map unit proportions and 75% +/- 10% spatial accuracy where training sets are optimally balanced,  uncertainty in classification is accounted for using a fuzzy membership adjustment and potential misalignment of ground truth and prediction locations has been accounted for. This sample design and analysis approach can be adapted to other inventories where map units can be assessed by line-intercept. We conclude that the presented methods will make implementation of comprehensive and reliable ecosystem mapping programs affordable, feasible to implement , and more accurate compared to manual and semi-automated methods currently used in British Columbia.


